# Generated by Django 5.2.7 on 2025-11-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_promotion_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='promotion',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
