# Generated by Django 5.2.7 on 2025-11-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_full',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
