# Generated by Django 5.2.7 on 2025-11-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_stripe',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
