# Generated by Django 5.2.7 on 2025-11-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosform',
            name='cep',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='infosform',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
