# Generated by Django 5.2.7 on 2026-01-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_create_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_update_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
