# Generated by Django 5.2.7 on 2026-01-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
