# Generated by Django 5.2.7 on 2026-01-02 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('product', '0002_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.variation'),
            preserve_default=False,
        ),
    ]
