# Generated by Django 5.2.7 on 2026-01-21 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user'], name='accounts_ad_user_id_46db89_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['cep'], name='accounts_ad_cep_144eea_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_address_name_per_user'),
        ),
    ]
