# Generated by Django 5.2.7 on 2025-12-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_inventory_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
