# Generated by Django 5.2.7 on 2026-02-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
