# Generated by Django 5.2.7 on 2026-01-15 21:23

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0002_photos_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_1', models.CharField(max_length=60)),
                ('link_2', models.CharField(max_length=60)),
                ('link_3', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('short_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Photos',
            new_name='Pricipal',
        ),
        migrations.RenameField(
            model_name='pricipal',
            old_name='name',
            new_name='name_shop',
        ),
    ]
