# Generated by Django 5.2.7 on 2025-10-19 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0003_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_code',
            name='code',
            field=models.CharField(default='7RLC2WMOI5ZIZ5A', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='payment_code',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
