# Generated by Django 5.2.7 on 2026-01-15 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0003_footer_rename_photos_pricipal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='link_1',
            new_name='who_we_are',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='link_3',
        ),
    ]
