# Generated by Django 5.2.7 on 2026-01-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0004_rename_link_1_footer_who_we_are_remove_footer_link_2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pricipal',
            new_name='Principal',
        ),
        migrations.AddField(
            model_name='banners',
            name='banner_mobile',
            field=models.ImageField(default=1, upload_to='banners/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='who_we_are',
            field=models.CharField(max_length=500),
        ),
    ]
