# Generated by Django 5.2.7 on 2026-01-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0005_rename_pricipal_principal_banners_banner_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='who_we_are',
        ),
    ]
