# Generated by Django 5.2.7 on 2026-02-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Item Carrinho', 'verbose_name_plural': 'Itens Carrinhos'},
        ),
    ]
